// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternating_text: dynamic(() => import("./AlternatingText")),
  carousel: dynamic(() => import("./Salles")),
  hero: dynamic(() => import("./Hero")),
};
